config/routes.rb
Airport::Application.routes.draw do
  resources :planes, only: [:index, :new, :show] do
    collection do
      post :launch
      get :history
    end
  end

  root to: 'planes#index'
end

app/models/plane.rb
class Plane < ActiveRecord::Base
  PERCENTAGE_PER_LAUNCH = 10

  attr_accessible :name, :launched_percentage

  validates :name, presence: true
  validates :launched_percentage, numericality: { greater_than_or_equal_to: 0, less_then_or_equal_to: 100 }

  scope :not_launched, -> { where { state != 'in_the_air' } }
  scope :launched, -> { where { state == 'in_the_air' } }

  scope :by_creation, -> { order 'created_at DESC' }
  scope :by_lauch, -> { order 'updated_at DESC' }

  state_machine :state, initial: :on_the_ground do
    event :be_ready do
      transition on_the_ground: :waiting
    end

    event :launch do
      transition waiting: :launching
    end

    event :launched do
      transition launching: :in_the_air
    end

    after_transition on: :be_ready do |plane|
      PlaneLauncher.perform_async plane.id
    end
  end

  def launch!
    self.launched_percentage += PERCENTAGE_PER_LAUNCH
    save
  end

  def launched?
    launched_percentage == 100
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  respond_to :html, :json

  def index
    @planes = Plane.not_launched.by_creation
    respond_with @planes
  end

  def history
    @planes = Plane.launched.by_lauch
    respond_with @planes
  end

  def new
    @plane = Plane.create name: Faker::Internet.domain_word
    redirect_to action: :index
  end

  def show
    @plane = Plane.find params[:id]
    respond_with @plane
  end

  def launch
    Plane.where(id: params[:planes]).each(&:be_ready)

    redirect_to action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planes_helper.rb
module PlanesHelper
  def percentage_text(plane)
    if plane.on_the_ground?
      t 'planes.plane.on_the_ground'
    elsif plane.waiting?
      t 'planes.plane.waiting'
    elsif plane.launching?
      t 'planes.plane.launching', percentage: plane.launched_percentage
    elsif plane.in_the_air?
      t 'planes.plane.in_the_air'
    end
  end
end

app/views/layouts/application.html.slim
doctype
html
  head
    title Airport
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    = yield

app/views/planes/_history_plane.html.slim
tr
  td = history_plane.name
  td = percentage_text history_plane

app/views/planes/_plane.html.slim
tr data-launching="#{plane.waiting? || plane.launching?}" data-plane-path="#{plane_path plane}"
  td = check_box_tag 'planes[]', plane.id if plane.on_the_ground?
  td = plane.name
  td data-percentage=true = percentage_text plane
  td = link_to t('.launch'), launch_planes_path(planes: [plane.id]), remote: true, method: :post, data: { launch_plane: true } if plane.on_the_ground?

app/views/planes/history.html.slim
.buttons.row-fluid.show-grid
  = link_to planes_path do
    .span12 = t('planes.plane.on_the_ground')

table.table.planes
  tr
    th = t '.name'
    th = t '.state'
  = render partial: 'history_plane', collection: @planes

app/views/planes/index.html.slim
.buttons.row-fluid.show-grid
  = link_to new_plane_path do
    .span4  = t('.new')
  = link_to '#', data: { launch_all: true }  do
    .span4 = t('.launch_selected')
  = link_to history_planes_path do
    .span4 = t('.history')

= simple_form_for :planes, url: launch_planes_path do |f|
  table.table.planes
    tr
      th = t '.selected'
      th = t '.name'
      th = t '.state'
      th = t '.actions'
    = render @planes